source = frappe.conf

background {
    path = ~/Pictures/wallpaper/a.jpg
    noise = 0.02
    blur_passes = 2
    brightness = 0.4
}

general {
    hide_cursor = true
    disable_loading_bar = true
    ignore_empty_input = true
}

input-field {
    monitor =
    size = 250, 60
    outline_thickness = 2
    dots_size = 0.2
    dots_spacing = 0.35
    dots_center = true
    outer_color = $sky
    inner_color = $base
    font_color = $text
    fade_on_empty = false
    rounding = -1
    check_color = $red
    hide_input = false
    position = -710, -200
    halign = center
    valign = center
}

label {
  monitor =
  text = cmd[update:1000] echo "$(date +"%A, %B %d")"
  color = $sky
  font_size = 22
  font_family = Iosevka NFP
  position = -710, 300
  halign = center
  valign = center
}

label {
  text = $TIME12
  color = $sky
  font_size = 60
  font_family = Iosevka NFP
  position = -710, 200
  halign = center
  valign = center
}
