source = frappe.conf

background {
    path = /home/gale/Pictures/out/dragon-girl_catppuccin-frappe.png
    blur_passes = 1
    contrast = 1
    brightness = 0.4
    vibrancy = 0.8
    vibrancy_darkness = 0.4
}

general {
    no_fade_in = false
    no_fade_out = false
    hide_cursor = false
    grace = 0
    disable_loading_bar = true
}

input-field {
    monitor =
    size = 250, 60
    outline_thickness = 2
    dots_size = 0.2
    dots_spacing = 0.35
    dots_center = true
    outer_color = $sky
    inner_color = $base
    font_color = $text
    fade_on_empty = false
    rounding = -1
    check_color = $red
    hide_input = false
    position = -710, -200
    halign = center
    valign = center
}

label {
  monitor =
  text = cmd[update:1000] echo "$(date +"%A, %B %d")"
  color = $sky
  font_size = 22
  font_family = MonaspiceRn NFP
  position = -710, 300
  halign = center
  valign = center
}

label {
  text = $TIME12
  color = $sky
  font_size = 60
  font_family = MonaspiceRn NFP
  position = -710, 200
  halign = center
  valign = center
}

shape {
    monitor =
    size = 500, 1080
    color = rgba($baseAlphaaa)

    position = 0, 0
    halign = left
    valign = top
}
