return {
	"gh:folke/snacks.nvim",
	setup = function()
		local set = vim.keymap.set

		set("n", "<leader>sf", function()
			Snacks.picker.smart()
		end, { desc = "Smart Find Files" })
		set("n", "<leader><leader>", function()
			Snacks.picker.buffers()
		end, { desc = "Buffers" })
		set("n", "<leader>sg", function()
			Snacks.picker.grep()
		end, { desc = "Grep" })

		set("n", "<leader>fc", function()
			Snacks.picker.files({ cwd = vim.fn.stdpath("config") })
		end, { desc = "Find Config File" })
		set("n", "<leader>ff", function()
			Snacks.picker.files()
		end, { desc = "Find Files" })
		set("n", "<leader>fg", function()
			Snacks.picker.git_files()
		end, { desc = "Find Git Files" })
		set("n", "<leader>fp", function()
			Snacks.picker.projects()
		end, { desc = "Projects" })

		set("n", "<leader>gb", function()
			Snacks.picker.git_branches()
		end, { desc = "Git Branches" })
		set("n", "<leader>gl", function()
			Snacks.picker.git_log()
		end, { desc = "Git Log" })
		set("n", "<leader>gL", function()
			Snacks.picker.git_log_line()
		end, { desc = "Git Log Line" })
		set("n", "<leader>gs", function()
			Snacks.picker.git_status()
		end, { desc = "Git Status" })
		set("n", "<leader>gS", function()
			Snacks.picker.git_stash()
		end, { desc = "Git Stash" })
		set("n", "<leader>gd", function()
			Snacks.picker.git_diff()
		end, { desc = "Git Diff (Hunks)" })
		set("n", "<leader>gf", function()
			Snacks.picker.git_log_file()
		end, { desc = "Git Log File" })

		set({ "n", "x" }, "<leader>sw", function()
			Snacks.picker.grep_word()
		end, { desc = "Visual selection or word" })

		set("n", '<leader>s"', function()
			Snacks.picker.registers()
		end, { desc = "Registers" })
		set("n", "<leader>sb", function()
			Snacks.picker.lines()
		end, { desc = "Buffer Lines" })
		set("n", "<leader>sc", function()
			Snacks.picker.command_history()
		end, { desc = "Command History" })
		set("n", "<leader>sC", function()
			Snacks.picker.commands()
		end, { desc = "Commands" })
		set("n", "<leader>sd", function()
			Snacks.picker.diagnostics()
		end, { desc = "Diagnostics" })
		set("n", "<leader>sD", function()
			Snacks.picker.diagnostics_buffer()
		end, { desc = "Buffer Diagnostics" })
		set("n", "<leader>sh", function()
			Snacks.picker.help()
		end, { desc = "Help Pages" })
		set("n", "<leader>sH", function()
			Snacks.picker.highlights()
		end, { desc = "Highlights" })
		set("n", "<leader>si", function()
			Snacks.picker.icons()
		end, { desc = "Icons" })
		set("n", "<leader>sj", function()
			Snacks.picker.jumps()
		end, { desc = "Jumps" })
		set("n", "<leader>sk", function()
			Snacks.picker.keymaps()
		end, { desc = "Keymaps" })
		set("n", "<leader>sl", function()
			Snacks.picker.loclist()
		end, { desc = "Location List" })
		set("n", "<leader>sm", function()
			Snacks.picker.marks()
		end, { desc = "Marks" })
		set("n", "<leader>sq", function()
			Snacks.picker.qflist()
		end, { desc = "Quickfix List" })
		set("n", "<leader>sR", function()
			Snacks.picker.resume()
		end, { desc = "Resume" })
		set("n", "<leader>u", function()
			Snacks.picker.undo()
		end, { desc = "Undo History" })
		-- LSP
		set("n", "gd", function()
			Snacks.picker.lsp_definitions()
		end, { desc = "Goto Definition" })
		set("n", "gD", function()
			Snacks.picker.lsp_declarations()
		end, { desc = "Goto Declaration" })
		set("n", "gr", function()
			Snacks.picker.lsp_references()
		end, { desc = "References" })
		set("n", "gI", function()
			Snacks.picker.lsp_implementations()
		end, { desc = "Goto Implementation" })
		set("n", "gy", function()
			Snacks.picker.lsp_type_definitions()
		end, { desc = "Goto T[y]pe Definition" })
		set("n", "<leader>ss", function()
			Snacks.picker.lsp_symbols({ layout = { preset = "sidebar" } })
		end, { desc = "LSP Symbols" })
		set("n", "<leader>sS", function()
			Snacks.picker.lsp_workspace_symbols()
		end, { desc = "LSP Workspace Symbols" })

		require("snacks").setup({
			bigfile = { enabled = true },
			input = { enabled = true },
			picker = { enabled = true },
			quickfile = { enabled = true },
			statuscolumn = { enabled = true },
		})
	end,
}
